apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-provisioning
  namespace: jupyterhub
  labels:
    demo: mongo-pv-provisioning
  annotations:
    volume.alpha.kubernetes.io/storage-class: any
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 200Gi
